apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAl4wFa21Ce8MaODpcxvfyL30mibHWc9h6DglxNmxKmHgUzWYclwDZwX6Y+zlmbccuethsKQw5UaoAauferiZzdpVS8gMcarEYMOwvCg+3k2/F+1TIUKOhogVKqnEoGcegzFFR4SPkFcsj9Nb7u3uF5f1TxlYfjF8wJTDxtXjyCpI0yinD+0CMJw4PRLWG5bWG6qk3eqyvKV0mPiQojqioMXv+S0VEK2sp2uSit7RmLYykGyz4mUWhNG2EqAgLvq4kvVUPIx4OIY/MUS+E16rI/6YyxOZ/8vZrYfiZPjunxEXcmlOl4khAorzndsAgd8FoXT+90jtik5Xc+Q+jyMrXnyQOLQBD8/AdwAcUSc+dtWTy5kQRhTuwOw7e0J32sUJuRPk490iP+WwsLfplzSs3leAm0SCf4vXc9eb29iSb1uohwvgCDGqelakkc2eW7lil0iacGRcr62cLG/3JGBBbMu0v0XjwqapmHfjikGLq4O7VXBVNAkwkQYqPInue+8fbbg7+3Z5x4xQacNXAEBoDM+b3K4w++lqKA8+QDQ6Dx/ZNrCEMwMlzg5KNgQ8o5AP88uTkv2jehFRcZXkF9Mf4nC7TFfKU/ndz0sbsKBR7qMr+0zT8qcsxA2eeKmpZEx63HAe5hw/vNVpERdaUeAxVNWebO5uCSlut7ot4vhpocgIV2e5cg9CoIfIn4MPMpNqA9RRnuq5yTUIphYHfAKLfLBEfs3jIk/Q4o0cRr+Y3xHSp6nW8sjahHjz4Uu0OFTKFQN1dxBfePPUQLGurdybDeZmzRLvtZKqDysGvxb4tSwcztmWN151MUuOaV7pVYFK+I16G4IoDVo1cPfqwlyU3r0Xb28JpHi8B/mW0eKUsno7kg4MC1tp5Rl5Z9YGyikY05fnDnWflWeRUnHdE9FyqJZB5IaakVuqgJzT3L9ZpmBSfhXutdgqjmV+1ChjM7wVqnIqOPppy27yJU6nDJpqnpw00=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

