apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCOy5hsqO0TjA2b9K06Fmn11lk6uekvuziWka4L7H5yrtPGp1M3B5PJS4sTVfNV4JeEaoH4rWBUKCTI6SieuCSVw2NX2tnvK0n5NogUYntmmj+iB6DmeEbjOqL3rKLypkgiZWUpQjKEwSeUNLymgKhwdRdDwH6OSeUtlgBU7/MxnOx1Sn0BhJ+7rCRNPFINphzE2jlkmDZZ8QyLLjbbv70ySGtpyQxVr4+UhAYDvn9xyHZ/MLTM7k0pmOdp65sNy+T2Zz/BGNEdIqoP6wItEailvsYTL2g4MVmKOBe+c7nHWpvg7e7eJ2zS59gbYQAt3+jPkHBxSqyF66nzdPX9pN87Gr+G6nZWf9GpLojZpTb/J46bJ7HrATl/Qgiio6N2nhoM2BIc/a9IPXH4PyAmYTOIBiSsSn8eL5dTIIHcJiHsx+BOhxhOEURpu9rYCCcl6Bx3kUSdCaabhiChP1E3Q9pkdWG41yj4R0BERGAQ8te8z8gKoazwLCAAVX7gGgs1mi3s85dALSySOmc+V/o7vKZtfB9JbcJvvigH1OOfAZ7aMRSrd5583r95MvwoXd5jNcyTV1gd27dp5DPJhD6TfveK+Gk+i+DevFCWorN9Xlm6i350wK6U1b7kDZU20VVYrY/1Dx39x3NzzWDQb52D6DGkZNe3KJ06AZBf5XZDIc8FMDEAmfaWX8eRhj0qTUVJNuF73XzlBO7jBnxoW+tbEy1/MQDbkt4eeKZvQm11cbweK5LxCXzQtS3Bt71okDbXinFX9a0fRJJGoJGXAHmVEsMTKYrEfDDJ6BdLtP+hB2aaChm4rSX9P5sDRohGdo+BgBpVNQui5boYDAWxPrTkwOKhvQj6clsYn9AYOktp7zEWPs1fL6b+oWsyYyWBnZI9GvApIdjaVlJM/WlPyhOOiP3ZBINvvcHGn9n7IBP9Z1/GppQEmXgwlztmeDCLdcL/YninOb35a3VYCzdP1uh9NlBuwwk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

