apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCzuvASDWVuYIkOlrP1z8i2up6AU0ndJFqDPTerHCiCqxSAMin9vJ4Ky3wKpjXcsyHPdE5ycC4fQn/MF3NwiCpVsGOkdg5O7SHrGjZyqNrkgauGDXF6p279a7PKutQUKhYcORtLI0awksY2EMv18WtJ6p3j7adfZIKB2MVZD1GX7gIgEXbwWISNr57O33Ck8dzkU5Mj5thfrsbpuPLFFsGfzARwkVJ1rOu36pH4QQu8vmpl9u3ZKF/gV9jIGdO0gBds066wJ+brf8uJmrwwVe5+3Jc8+iOL2unbN66LYX37oRSPumvrUwzvy4l8lJ/3bAQVwSFbYc3Oq+VEvx7BvZTSplXOLogG1gZ1QPuR96fcrTlfFOfc2rlCmUAwmWbr0fl2oV8QKDmY6cN1AO2AkYYvdlT/9jJfbty/VZ7XQV8aAjpjXcQeujXDSEyV2UG+/9qsMIdqqb2fmDHOne6odEcbBpIiylJznjPalPAi3NSjIz6EPFipR4WH5yob63RHqQVR72mlIOI/lnLdM7vWb3aA67ItNzpn0zt4Vs4evObclIE89YY14/c02KpuPglDsk/5N2G8rz+DXBlev6AeS85oc4kjM2VnoemWXsEI1oYhufbxVRGTxU5d11hiPBKsu2LwQjwdUd8OOaGdZo8AOwJ4caGF95IUl/LgFwVed14TVwerqE4sx+ui9vYzUEGsv3sbGtARkdxmRc+VBdCmFILcUoMMJlGt/mmT1ChlYh3FKTVIE0Fw5yJBEIcTsm5g8byOfCEQWqXeZ71i22z16tBFGx5sWG44iI3VO1QzSUVis26o923NUHnlvQjOO9myZBVushetksvp1iRoRiwbuvnfImrGnJCHV88dA9AesqLHAYWyHEfkIfhjUyFOsWQ71nTmsmXFekRSGTbzteAt2HiTnoEVBkMmA0luN46VZR3I+UDAqQVHV/4UwV9639JEWF14OBs899iHp4NcJXml/6rkujo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

