apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAXtAxXS7MjLXpkKeecl8erWGUL/nb3AGxOlWsE03q+vBh1MWZShZNUtd6WIcFl3zTZYK+OVBfo6EYGQ/tx/ndLHvwrySzhQo0tOFrWYzmufyx+SuWfIuWAimb5ohAGUVSOk716o/BA4/yXfsLhiANdCZrdLOYep0yJVvinIAAAGXNPZeo/LV+tn1OzMezk/pGOMHoHszKsERLlweQsk3R7K6Cv1dLFxGK0tWdsaRUCBbnecl/mZpfTm8wOmL9vJvTL+L/FNDsdK6ajOb1nlq0vVrU6eK4qSHGALSIpQCZFLyEPsYGeEB2UA/6J7mWDaA1XmKF0OcXAiukXtb70uKAVV4HKmYJGn4Rl7MMWRRejwjE1FnvmzAkhcz6EEAPL6+6Bu3V0tdffmOVcgpJo7OVh4HOg2cr12gaYyFMKV5aIr9iAN/cJHV85jmtr2a3srmxSawzClbYeOS0iL5YH5PHCPbinyUtR2d+jF5UEEbfJoggcGKehxtQyYiJb1UjjBx/S7MLTmIO+Z0cMgf0+vVaOpHwtlaDpyAYPVJuvanS+yZJaGBsAX1FlOsHAq7i4rOkQBvFZBAkKx+Je47zlv7ATctgvzwJQxFdvmj3DByDrgzygOmLETbrdJK4IASMaPmT+TA8+LhvNrj4Se4QwUlzSiVSKGKE5b1cyn40Hknh8FKJc7cGN4Y4sndjRqTTmi24ZJpkmM6IS/cO/1iltDicM2NUynz8mA3p/la4BmAgQ70+F9J0mpzaCe0utq+IjXmMCV76oisfUCbTxOKf3kJLDO3O4kFOUwuEN4vh3aq4XJBPKiNupA20wJYeT11CsZcNiAzmPtmILfHvTcgq1tGD3NnZ8UWKLYDun01CD+j28o89OVn7nCbnBI5mViQiGHXK5JE7SEcu4dLzkhtgKX8lxyKW7a/4BpJNxwVc5z9jYVZ8RzlC+fVCyD42VfS7M+gLiVpmKEWmIFTpLHPsZxVCIXks=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

