apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDcjbQSqIQgOMIM2zpR4VMl+PgD6DbZHIPQTe36FKY9Q4QphVP/KUN74eOMya5QMIk0iBzCk9FVNJi5EmITAmnfC7g/2JHWn2gjtOnx+4v9AexKHhdMIkEh29PHjWJd9cGWxszkQoXFeRyiGLR734vc2FGQ5ssem20417JdQQKnnnrSdOzssd6MwB6HK6mle/TU328rMeQqmPSzVIBnR6WS71qHmei3cSR9iAjKNTb3OJvpa3BgHVQYkcbEbgF0nXQmDdTh1zocRmkHRu1W+wlRAG/uQaxikGGzyFvIkpy8ZRYEiT2+JPoEWkG0PflLWMTXw24LX/QBSHODOjyrEmyGe8OdI/wz12iU/IJOs+P4bfhkAh0ExnPMvT7lRubEMttNGoFDRaZSElvwUyo+l3MeyeaM9/5mVHak9+Gdzym4aoea7HFQyxgVlD1aiNHfM9JYXhTsyogVrZ91EbhchyBlkEf/bCg3Nz6cTD6Nkzsb2Jmv6jbC0WfQGCf5vUKq7Cn0IaHsdqpY9L/6XPPLiGIyx7VG04kiGmlHUdF3fSM4THtjyDy6ezmf9VKgcvx0qNa/7HMwPya+vqDGxrqQFAcmjTELkaSzDGznqq7AmgaXF2naPGnhJojb5K70tZIwHCKtTpB9v4ElSO9wD7yC7+gPba/9fJHzot03m2lUtSX1aU2Emsir3X0neIZ1KZmUq9HSXxZALUWGyQZqog9owxu9hRBFi3Bd0psWyt3ZXEwens+D8lVMidtd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

