apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBHXunKL9Tzt+jLf00rXqGdUZKmj47wkwlDCw0LOxmUpE5rX2+ZWl2kxqQFTEEiE3HiE6jnLXe+cGGo9b0kTSyj3BUt/fSQ0E3wkgaWv+Fx2z3RwT/K3z4YJOzKob3AJllIho9Xw/Ge7/wZY4vsNcs+yINhC1f71YgFby8Tw7I9IdUIYoKPD7EU+fzkgXNH5K7GMfFrt7+AaQkhLbbPu3eC8+ljgyBR0yI19z/wf9A/rx9CDo5nvehJPfYCsXwi8MqUmRARPYEljug+G8p1iyGsOfDWc9ELl8zhTm2m2UplDtEMqvQiaIQNKa6sNIFOFhNda2n/vPD/X7Ck8iGvB3ocsVlhfxJ7JEDa/iX/jybOg/wexcv5z2Dz0RF6nl7Y0HZ8CYOXWDAWylafZR9+b1Hdj98IpCTONYCaOFknpxxycP8tnlHOuBB2Ed96Gp4pYV6vS161oNwC9Z0e2Inb2PgVSbaaSqZHv+CjkdlrB/LeBp1I28dGrGAuomawl7lZkd38ccHOFcX/Rim99vMu8l3wB36e1NZOdpQr9HiOyCLypv336QP4wWP6SJpymNIiPjf4WBsv5wzz64+pC1y6vgLljnyv1J0o0ozkINg1Qp5oUSVF1UYa9UJC9Rp+v8pnRxjyrryU4h7b+mEGG1No7sDMhk0WbmW2XEp6qTu/tfJIdsFh7LtQeJF6Y1JejayiTm1zIQvi7ZQX3EtP9SJMvw0PJREWzmYZQjviOpC5bNXCBML5hS89MWNf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

