apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgClPrLep8aCkkbP47rwAawxBjjkQzhSJvF7lalI5GeSt/p9m9mePiwoIlihWvx1of2kSBijL/KGQjZZPuhnWv/KYOdApdGRWvQvt58TXZK6cc7WLqLqIvTxA6H/ZYLsznlCeyt9KkQPf5ZdW/YzSom7HfRwQM3NARiKFSNgB0iPp8Q1fRCnbB/UvDajo77fOFbrQ6MSRXQq40726K72upcmuZPY/uNbhd9+O5HWE24V45+S47xIaix6XRxGYTmBzedvxsZLEnp+6XeG8VXkXhSuKr49/GWvLXZj6u6VkyG0i8qtolYXHfhE5UkB0ITFJA9vhk+qynrUtLEkoscC415TvlpunzzYd6nVE1+HCnOiCDlN0nXBbszP2CDgudBD4r8l2ZrnpYkCoa0CYi0ecYEsNIz3NFkhrJCaadNXAlxjO3MMTOs4K18MV3rQQGjQaWZqYOeN7qNrTCxfzwtZeKOO/6JQrkovmjEMlrvPVobUvm3Rb3KykFvvcP98EQu2OkP3nTY8iM0VbiYpVQcbvNUq9RwUJGRlqzRL5oCJVQHQlKdH8J2oBfK2HCgCoi8xu71Q+9YTpoqbXdPi74c5tbczZnp4BfxNtYCbcTvHmpl7qLAAcBDzbQczf2HpZ/lokZ7lVRyrPBipkQE2XDO6AnSkjyz9FF1jo1UVxH1jY6G21mPAgH38pgTLHC3pxOZCGSUS/WnsNMdwN+IToia+GGoiwWyQYASMVKuVBjk5+8NbVApS9IHHnchJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

