apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBv+HSnUk7ZcWaIuRohTJSklEOOQzglHvRZSdLbGmeOvlSeLch0m7GS55tOMzsRjjkW5D7tGBAg+cTYYdQabK8wkQzJ7VJfJkYH5wHM4zY8M10K6qghG/aIxKHW95uKyiniIByyRHvzH/id51180OinO5w4vRILA6ePuCyiqMoutE2JoXkmAT2gTi0TpLYm6yGbmq1yhSPNZLJNuLGChVV+zTC/xzyXkckUlEPK8RkYj3ygiDOgTeYX80mAPsSTAyFbtVOcE0Mglfli6cScvnbzOL8TQ/veTmh1IePzv4EY1SNFcv8zU9lUxCv/KGjwjr8hZ1VnbcvpweRYmxHQaOC0MP0EBK4SqCWoPqLHCJVMr3aizG5XXUdo0IqojyrAaM7SWJsU+vYv/0L4KzKZWlMeAFMQ6t6NuaepyaQ9cnl2d3rZ0+pYQp0yCgQGKoWEwvVWOPgGGXElEHDnZgZul1RQWTGcWgmifX5XjgvHPjILHG7MeiTKnuS6cyrm5TkjSlkIwR/jmUv8f89peyxJl5yeMfRGl3Q2RJcGkyM7aq00+KoOMt9rZSOEo54MLG1BgyNIS6mNEo0vcnHSwfn+Rd4hogr+e3arRScRaMEqGb7rZuhWTAEXbVoV/9JoeL8kLmxOPmgETSCW4ZI4Gx4AlWJLTjQtzkXSaLpi1Orn9CWEGqIuxfpDDdma8AEnXYncYFvndm3Rr96aLTM4D40Ii75gBkuA0UvvJrB3n9/DjbNOLO6sQjp/Xyjx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

